config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get "home/about" => "homes#about"
  resources :users, only: [:show,:index,:edit,:update, :create]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
 end
  resource :relationships, only: [:create, :destroy, :show]
  resources :users do
    get :followings, on: :member
    get :followers, on: :member
  end
  
  get "search" => "searches#search"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  attachment :profile_image, destroy: false

  validates :name, presence: true,
  length: { in: 2..20 }, uniqueness: true
  validates :introduction,length: { maximum: 50}

  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # @user.booksのように、@user.yyyで、
  # そのユーザがフォローしている人orフォローされている人の一覧を出したい
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def following?(follower)
    self.followings.include?(follower)
  end

  def follow(follower)
    unless self == follower
      self.relationships.find_or_create_by(followed_id: follower.id)
    end
  end

  def unfollow(follower)
    relationship = self.relationships.find_by(followed_id: follower.id)
    relationship.destroy if relationship
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path(resource)
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!
  def show
    @book = Book.find(params[:id])
    @post_comment = PostComment.new
  end

  def index
    @books = Book.all
    @book = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render:edit
    else
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end


  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

   def search
    @range = params[:range]

      if @range == "User"
        @users = User.looks(params[:search], params[:word])
      else
        @books = Book.looks(params[:search], params[:word])
        
      end
   end
end
# 前方一致
#モデル名.where("カラム名 LIKE ?", "値%")
# 後方一致
#モデル名.where("カラム名 LIKE ?", "%値")
# 部分一致
#モデル名.where("カラム名 LIKE ?", "%値%")

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @relationship = current_user.relationships.find_by(followed_id: @user.id)
    @set_relationship = current_user.relationships.new
  end

  def index
    @users = User.all
    @book = Book.new
    @set_relationship = current_user.relationships.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render:edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
     @user.update(user_params)
    if @user.save
       redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      @users = User.find(params[:id])
      render :edit
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.all
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_user_messages.html.erb
<% if user.errors.any? %>
 
  <div class="alert">
    <ul>
      <% user.errors.full_messages.each do |message| %> 
        <li> error <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if book.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h3>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' Users',users_path,class: 'fas fa-users nav-link text-light' %></li>
          <li><%= link_to ' Books',books_path ,class: 'fas fa-book-open nav-link text-light'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'fas fa-sign-out-alt nav-link text-light' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'fas fa-home nav-link text-light' %></li>
          <li><%= link_to ' About',home_about_path,class: 'fas fa-link nav-link text-light' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'fas fa-user-plus nav-link text-light' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'fas fa-sign-in-alt nav-link text-light'%></li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<%if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>
<% if user_signed_in? %>
  <div class="search_form col-xs-6 col-xs-offset-3 text-center" >
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backword_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <p id="notice"><%= yield %></p>
      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>